### ISSUE TITLE
Implement JS for Move From/To Button

### ISSUE THREAD

**Issue by terri-hewitt** [cs361fall2017/team27#14]
When the user clicks "Move From", flip the other buttons to "Move To".  When "Move To" is clicked, move the card from the "Move From" column to "Move To". Reset buttons to "Move From".

**Comment by Lucas-Campos-Davis** [comment]
you could use disabled buttons section here: https://www.w3schools.com/css/css3_buttons.asp for the remove button when the move button is pressed
